# Generated by Django 4.1 on 2024-01-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('usia', models.FloatField()),
                ('berat_badan', models.FloatField()),
                ('tinggi_badan', models.FloatField()),
                ('status_gizi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BalitaDiskritis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('usia', models.FloatField()),
                ('berat_badan', models.FloatField()),
                ('tinggi_badan', models.FloatField()),
                ('status_gizi', models.CharField(choices=[('Gizi Buruk', 'Gizi Buruk'), ('Gizi Kurang', 'Gizi Kurang'), ('Gizi Normal', 'Gizi Normal'), ('Gizi Lebih', 'Gizi Lebih')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BalitaPengujian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribut_tambahan_pengujian', models.CharField(max_length=255)),
                ('balita_diskritis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.balitadiskritis')),
            ],
        ),
        migrations.CreateModel(
            name='BalitaPelatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribut_tambahan_pelatihan', models.CharField(max_length=255)),
                ('balita_diskritis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.balitadiskritis')),
            ],
        ),
    ]
